services:
  - type: web
    name: ai-travel-booking
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: GROQ_API_KEY
        sync: false

      - key: TAVILY_API_KEY
        sync: false

      - key: AVIATIONSTACK_API_KEY
        sync: false